# Tool to build various other packages:
usr/bin/wayland-scanner

# Headers:
usr/include

# Use no wildcards to ensure we spot any update:
usr/lib/*/libwayland-client.a
usr/lib/*/libwayland-client.so
usr/lib/*/libwayland-cursor.a
usr/lib/*/libwayland-cursor.so
usr/lib/*/libwayland-server.a
usr/lib/*/libwayland-server.so
usr/lib/*/pkgconfig/wayland-client.pc
usr/lib/*/pkgconfig/wayland-cursor.pc
usr/lib/*/pkgconfig/wayland-server.pc
usr/share/aclocal/wayland-scanner.m4
usr/share/aclocal/wayland-scanner.mk
